"""Migration Inicial

Revision ID: 47ddd0882aeb
Revises: 
Create Date: 2026-02-06 17:59:42.814241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47ddd0882aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_perfil'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_perfis_valor'), 'perfis', ['valor'], unique=True, schema='auth')
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_pass', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['auth.perfis.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_usuario_email'), 'usuario', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_usuario_uid'), 'usuario', ['uid'], unique=True, schema='auth')
    op.create_table('tokens',
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['auth.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_token'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_tokens_token'), 'tokens', ['token'], unique=True, schema='auth')
    #op.drop_table('alembic_version', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='auth'
    )
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='tokens', schema='auth')
    op.drop_table('tokens', schema='auth')
    op.drop_index(op.f('ix_auth_usuario_uid'), table_name='usuario', schema='auth')
    op.drop_index(op.f('ix_auth_usuario_email'), table_name='usuario', schema='auth')
    op.drop_table('usuario', schema='auth')
    op.drop_index(op.f('ix_auth_perfis_valor'), table_name='perfis', schema='auth')
    op.drop_table('perfis', schema='auth')
    # ### end Alembic commands ###
